-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIKa5+PGF0GSuXQM0
1sweVutu2d5xBQ+fg7ZdHG6kTiegCgYIKoZIzj0DAQehRANCAARmrjY7pDbwUVmt
bRAc5iFEnbnSzo1fviIaY1F3iKu9OQb+tzup0Uxo9DmhL6PtLvVCS5WXh+b4ZtxI
WBbttSz3
-----END PRIVATE KEY-----