#spring:
#  profiles:
#    active: local
#  messages:
#    basename: i18n/exception
#    basename2: fabric/init_dev
#    encoding: UTF-8
logging:
  level:
    root: info
  file:
    name: ./logs/local-log.log
    max-size: 1MB
    max-history: 30
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n"
    file: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n"
    rolling: ./logs/local-log-%d{yyyy-MM-dd-HH-mm-ss}_%i.log.gz
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
spring:
  redis:
    host: jwtrefreshtoken.7pxmxz.ng.0001.apn2.cache.amazonaws.com
    port: 6379
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:mysql://toyproject.cttbvjkpsby1.ap-northeast-2.rds.amazonaws.com/did
    username : admin
    password : wl1156414
  servlet:
    multipart:
      enabled: "true"
server:
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: ENC(3/XRfLOBrBs+JodQ/mgB9Q8c1zOqCcvmb7eatvB7+xbVlWZKEEoLUgzH5mBNBBqI)
#    key-store-type: PKCS12
#  http2:
#    enabled: true
  port: 9090
issuer:
  name: ENC(lYAKu7JvLBnC/+LO7frZ/pwfIh2rE36Sa1lX0Lcoigk4xg29VEsV3Otpv7zU8lv/)

contract:
#  key: ENC(brtRxwPkjXSUe3MkAxBqWhcg4oX00m1GoYFq8dWbDs7e12uXf2c8q4yIfyOcVyFsIi0Y6mIsYSOW+u9xQ9NGi4ceL6NBSaXLCTzcqHkgCNyJVPzRSaT2uFxh129eJu6SeQeLBtArNlTMqfe0pafNNA==)
  key: ENC(hZxxYbrgQADP1iadshRAAszsN+dzmggAuztgzoTHBQoraJj5E+O/eZMVXb1sdcHU17oRGfsFuBZT1PiCGKQq2a/ALpnaWo+JQvnCcUMebJWtxZl0tGlCOT+yUOjuIxTQ9M2Km1IpwCPp/gCzVsLuCA==)

